version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: rails
    versions:
    - 6.1.3.1
- package-ecosystem: bundler
  directory: "/test/rails_52"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: rails
    versions:
    - 5.2.4.5
    - 5.2.5
    - 6.1.3.1
- package-ecosystem: bundler
  directory: "/test/rails_61"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
